# Generated by Django 5.0.4 on 2025-06-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
