# Generated by Django 5.0.4 on 2025-06-09 18:21

import posts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, validators=[posts.validators.NotValidDepartmentValidator(fake_department=['porn'])]),
        ),
    ]
