# Generated by Django 5.0.4 on 2025-06-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='date',
            field=models.DateField(),
        ),
    ]
