# Generated by Django 5.0.4 on 2025-06-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_department_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='input_date',
            field=models.DateTimeField(default='2025-06-09 23:05:32'),
        ),
    ]
