# Generated by Django 5.0.4 on 2025-06-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_department_input_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='input_date',
            field=models.DateTimeField(default='2025-06-09 23:09:59'),
        ),
    ]
