# Generated by Django 5.0.4 on 2025-06-09 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_alter_department_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='input_date',
            field=models.DateTimeField(default='2025-06-10 01:54:40'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
