# Generated by Django 5.0.4 on 2025-06-09 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_alter_department_input_date_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='departments/'),
        ),
        migrations.AlterField(
            model_name='department',
            name='input_date',
            field=models.DateTimeField(default='2025-06-10 01:57:36'),
        ),
    ]
