# Generated by Django 5.2.3 on 2025-06-22 09:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_event_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 22, 9, 20, 7, 75397)),
        ),
    ]
